image: node:latest  

stages:
  - build

pages:
  stage: build
  script:
  - npm install
  artifacts:         #Luego de instalar los modules,exportamos un artifacts
    expire_in: 1hr   #dicho artifact solo vivira por una hora
    paths:
      - node_modules/   #Ruta de lo que vamos a exportar
  cache:
    paths:
      - node_modules/ #Lo guardamos en cache, para no pasar instalando node modules cada rato

